// <auto-generated />
using System;
using Mags.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mags.Migrations
{
    [DbContext(typeof(MagsContext))]
    [Migration("20210128160318_Receptie")]
    partial class Receptie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mags.Models.Comanda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EANID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EANID");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("Mags.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Inaltime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Latime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Lungime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Mags.Models.Receptie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EANID")
                        .HasColumnType("int");

                    b.Property<string>("EAN_Produs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Furnizor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSCC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EANID");

                    b.ToTable("Receptie");
                });

            modelBuilder.Entity("Mags.Models.Stoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComandaID")
                        .HasColumnType("int");

                    b.Property<int?>("EANID")
                        .HasColumnType("int");

                    b.Property<string>("Furnizor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceptieID")
                        .HasColumnType("int");

                    b.Property<string>("SSCC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ComandaID");

                    b.HasIndex("EANID");

                    b.HasIndex("ReceptieID");

                    b.ToTable("Stoc");
                });

            modelBuilder.Entity("Mags.Models.Comanda", b =>
                {
                    b.HasOne("Mags.Models.Produs", "EAN")
                        .WithMany()
                        .HasForeignKey("EANID");
                });

            modelBuilder.Entity("Mags.Models.Receptie", b =>
                {
                    b.HasOne("Mags.Models.Produs", "EAN")
                        .WithMany()
                        .HasForeignKey("EANID");
                });

            modelBuilder.Entity("Mags.Models.Stoc", b =>
                {
                    b.HasOne("Mags.Models.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaID");

                    b.HasOne("Mags.Models.Produs", "EAN")
                        .WithMany()
                        .HasForeignKey("EANID");

                    b.HasOne("Mags.Models.Receptie", "Receptie")
                        .WithMany()
                        .HasForeignKey("ReceptieID");
                });
#pragma warning restore 612, 618
        }
    }
}
